[workspace]
members = ["crates/*"]

[workspace.dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[package]
name = "mia-info-poc"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
resolver = "3"

[dependencies]
axum = "0.8"
serde = { version = "1.0", features = ["derive"]}
tokio = { workspace = true }
