[workspace]
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[package]
name = "mia-info-poc"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
resolver = "3"

[features]
listen_public = []

[dependencies]
ab_glyph = "*"
anyhow = { workspace = true }
axum = "0.8"
axum-prometheus = "0.8"
imageproc = { git = "https://github.com/image-rs/imageproc.git", branch = "master" }
mime = "*"
serde = { version = "1.0", features = ["derive"]}
tokio = { workspace = true }

[dev-dependencies]
magick_rust = "1.0"
mockall = "0.13"
rand = "0.9"
