{
 "title": "Mia Info",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Version Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(version_major, version_minor, version_patch) (mia_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(version_major) (mia_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(version_minor) (mia_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Patch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(version_patch) (mia_info)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}