[package]
name = "dev-client"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
anyhow = { workspace = true }
kitty_image = "0.1"
reqwest = { version = "0.12", features = ["blocking"] }
